In [ ]:
import tensorflow as tf  
import numpy as np  


def generar_matriz_tf(filas, columnas):  
    """Genera una matriz con TensorFlow con valores aleatorios entre 1 y 20.  

    Args:  
        filas: Número de filas de la matriz.  
        columnas: Número de columnas de la matriz.  

    Returns:  
        Un tensor de TensorFlow representando la matriz.  
    """  

    filas = int(filas)  
    columnas = int(columnas)  

    matriz_tf = tf.random.uniform(shape=(filas, columnas), minval=1, maxval=21, dtype=tf.int32)  

    return matriz_tf  


def sumar_matrices_tf(matriz_a, matriz_b):  
    """Suma dos matrices utilizando TensorFlow.  

    Args:  
        matriz_a: Un tensor de TensorFlow representando la primera matriz.  
        matriz_b: Un tensor de TensorFlow representando la segunda matriz.  

    Returns:  
        Un tensor de TensorFlow representando la suma de las matrices.  
    """  
    try:  
        suma_tf = tf.add(matriz_a, matriz_b)  
        return suma_tf  
    except tf.errors.InvalidArgumentError as e:  
        print(f"Error al sumar matrices: {e}")  
        return None  


def multiplicar_matrices_tf(matriz_a, matriz_b):  
    """Multiplica dos matrices utilizando TensorFlow.  

    Args:  
        matriz_a: Un tensor de TensorFlow representando la primera matriz.  
        matriz_b: Un tensor de TensorFlow representando la segunda matriz.  

    Returns:  
        Un tensor de TensorFlow representando el producto de las matrices.  
    """  
    try:  
        producto_tf = tf.matmul(matriz_a, matriz_b)  
        return producto_tf  
    except tf.errors.InvalidArgumentError as e:  
        print(f"Error al multiplicar matrices: {e}")  
        return None  

if __name__ == "__main__":  
      
    filas_a = int(input("Ingrese el número de filas para la matriz A: "))  
    columnas_a = int(input("Ingrese el número de columnas para la matriz A: "))  

    filas_b = int(input("Ingrese el número de filas para la matriz B: "))  
    columnas_b = int(input("Ingrese el número de columnas para la matriz B: "))  


    matriz_a_tf = generar_matriz_tf(filas_a, columnas_a)  
    matriz_b_tf = generar_matriz_tf(filas_b, columnas_b)    
    print("Matriz A:")  
    print(matriz_a_tf)  
    print("Matriz B:")  
    print(matriz_b_tf)  


    if matriz_a_tf.shape == matriz_b_tf.shape:  
      suma_tf = sumar_matrices_tf(matriz_a_tf, matriz_b_tf)  

      if suma_tf is not None:  
        print("Suma de las matrices:")  
        print(suma_tf)  
    else:  
        print("Las matrices no tienen las mismas dimensiones, no se pueden sumar.")  


    if columnas_a == filas_b:  
        producto_tf = multiplicar_matrices_tf(matriz_a_tf, matriz_b_tf)  

        if producto_tf is not None:  
            print("Producto de las matrices:")  
            print(producto_tf)  
    else:  
        print("Las dimensiones de las matrices no son compatibles para la multiplicación.") 

Matriz A:
tf.Tensor(
[[13 10]
 [17  6]], shape=(2, 2), dtype=int32)
Matriz B:
tf.Tensor(
[[9 6]
 [3 2]], shape=(2, 2), dtype=int32)
Suma de las matrices:
tf.Tensor(
[[22 16]
 [20  8]], shape=(2, 2), dtype=int32)
Producto de las matrices:
tf.Tensor(
[[147  98]
 [171 114]], shape=(2, 2), dtype=int32)
